1-create the request account page front end
Hack4Impact-UMD/jefferson-area-board-for-aging pull request #6
Opened 2023-10-23 02:57 UTC by kshah2020

## Changes
`App.tsx`
- replace Example Page with RequestAccountPage

`RequestAccountPage.tsx`
- main page containing front end to request a page
- component/features
  - fields for user to enter information 
  - radio buttons for create user as and priority fields
  - submits form/console logs when submit button is pressed
  - has popup appear to inform the request was sent
  - refreshes page to allow a new account to be set

`RequestAccountPage.css`
- css formatting for page/form fields to match figma layout

`popup.css`
- CSS styling for the popup (after submit is pressed), to appear as a popup window and match the styling/formatting on figma

## Dependencies
- n/a

2023-10-25 23:44 UTC, yieb commented on jaba/src/pages/ResourcePage/ResourcePage.module.css
Remove this file since this is a file not relevant for this specific PR

2023-10-25 23:45 UTC, yieb commented on jaba/src/pages/ResourcePage/ResourcePage.tsx
Remove this file since this is a file not relevant for this specific PR

2023-10-25 23:49 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
For consistency, can you rename the file to end in module.css

2023-10-25 23:51 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
Also make sure to rebase with main to make sure the custom fonts load in properly

2023-10-25 23:51 UTC, yieb commented on jaba/src/models/ResourceObject.ts
Remove this file from this PR since this is a file not relevant for this specific PR

2023-10-25 23:52 UTC, yieb commented on jaba/src/backend/firestoreFunctions.ts
Remove this file from the PR since this the changes are not relevant for this specific PR

2023-10-25 23:53 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
> +    background-color: #012146;
change hex code to #023C47

2023-10-25 23:57 UTC, yieb commented
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/a9cc8951-9214-46ee-94d3-5795e8d125b2)

When I load the page, the sizing is off

2023-10-25 23:58 UTC, yieb commented
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/7da111e6-2f5c-4368-b9a3-404d2df91a9b)

The size of the input boxes should not be able to be changed

2023-10-26 00:08 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
> +    border-radius: 25px;
Change border-radius to 6px;

2023-10-26 00:14 UTC, yieb commented
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/ab07ad84-e2f0-4410-88e8-75b9800d8117)

2023-10-26 00:17 UTC, yieb commented
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/4e7c1f4a-f118-469b-b038-1ae446c8c99a)

![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/8b11c56e-3dd3-41bf-b8ae-0c374808edb6)

Layout of input boxes is different

2023-10-26 00:19 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
> +    margin: 39px 769.57px 806px 62px;
Where are numbers coming from?

2023-10-26 00:21 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.tsx
> +                  <a className="click-here" onClick={resetPage}>
Can we make the cursor change here to make it more obvious that you can click here?

2023-10-26 00:28 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
> +    margin: 39px 769.57px 806px 62px;
What is the different between request page and request header? They both appear to wrap all the HTML code

2023-10-26 00:30 UTC, yieb commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
> +.heading-container {
Where are all the px values in the file coming from? Are all of them pulled straight from Figma or are some just numbers that were arbitrarily set so it looked nice?

2023-10-26 00:32 UTC, yieb commented
Sidenote: adding a screenshot of what the frontend looks like on your end would be very helpful to include when making your PR next time

2023-10-26 09:02 UTC, yieb requested changes
See comments

2023-10-26 23:00 UTC, andrewyang03 commented on jaba/src/pages/RequestAccount/RequestAccountPage.css
> +.heading-container {
They were generally pulled from the figma page

2023-11-05 10:57 UTC, yieb approved these changes

2023-11-05 11:01 UTC, yieb commented
Updated CSS styling. Final Result:
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/378413c2-f88f-48a4-a775-d02ab4417c94)

2023-11-05 11:01 UTC, merged