completed front end to both pages
Hack4Impact-UMD/jefferson-area-board-for-aging pull request #7
Opened 2023-10-25 20:25 UTC by SPTLAbron

I completed the front end for both pages and put them both in app.tsx

2023-10-27 15:22 UTC, RickyLi15 reviewed
Hey guys, overall your pages look good. There are just some typos, if you can compare them with the figma page that would be great. Also, the designers decided to go with a dark green color instead of blue. Please change that as well.

2023-10-28 07:37 UTC, yieb requested changes
It would be great if you could add more detail to the PR description and update the PR title to be more descriptive

Also it would be good if you could follow the example files in the repo and add your reset password .tsx + .css file in their own subdirectory under pages and similarly make another subdirectory for the files for the ForgotPassword page files

2023-11-01 08:18 UTC, yieb reviewed
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/3eb322e8-9d8b-4fce-b1d5-4a022dad5dde)

- The Reset Password page is missing the little eye icons in the input boxes. 
- There should also be a graphic on the right side of the page that is missing on both the Reset Password and Forgot Password pages

2023-11-01 08:18 UTC, yieb commented on jaba/src/App.tsx
> +import ForgotPassword from "./pages/ForgotPasswordFrontEnd";
You put your files in subdirectories under pages/ like I asked but you also need to update the import paths in the App.tsx file so errors don't occur on build

2023-11-01 08:18 UTC, yieb commented on jaba/src/pages/ForgotPassword/ForgotPasswordFrontEnd.module.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300&display=swap');
Can you see if you can rebase your branch with main and use the custom font files that were added to the repo instead of importing with the url?

2023-11-01 08:18 UTC, yieb commented on jaba/src/pages/ForgotPassword/ForgotPasswordFrontEnd.module.css
Can you rename the files without the "FrontEnd" endings? Those are a bit unnecessary

2023-11-01 08:28 UTC, yieb commented on jaba/src/pages/ResetPasswordFrontEnd.module.css
> +.login_section {
Remove these css styles - they are unused in this particular page

2023-11-01 08:29 UTC, yieb commented on jaba/src/pages/ResetPasswordFrontEnd.tsx
> +      <div className={classes.content}>
What is this content class? It is unused right now

2023-11-04 03:32 UTC, SPTLAbron commented
I made all the stated changes. I used online SVG's for seeing password or hiding password parts.

2023-11-05 11:12 UTC, yieb commented on jaba/src/pages/ForgotPassword/ForgotPassword.module.css
You did not rebase and switched to using the custom fonts that are in the main branch

2023-11-05 11:13 UTC, yieb commented on jaba/src/pages/ForgotPassword/ForgotPassword.tsx
> +import { ReactComponent as Logo } from '../image_6.svg';
Can you import the image with a more descriptive name

2023-11-05 11:13 UTC, yieb commented on jaba/src/pages/ForgotPassword/ForgotPassword.tsx
> +import classes from './ForgotPassword.module.css';
Can you update to use the syntax that Ricky messaged? Use styles instead of classes

2023-11-05 11:13 UTC, yieb commented on jaba/src/pages/ResetPassword/ResetPassword.tsx
> +  const [isVisible1, setIsVisible1] = useState(true);
Could we use more descriptive react state names?

2023-11-05 11:14 UTC, yieb commented on jaba/src/pages/image_6.svg
Can you update the name of this image to be a bit more descriptive in some way? Additionally, can you move this to the the assets directory?

2023-11-05 11:19 UTC, yieb commented
![image](https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/52669318/4f0a4738-3cc5-40f8-9d6a-88867b8b15b5)
Can you double check some of your styling? Some issue but for example, when I see the page, the input box where you type the email has overly rounded corners. I see you used em in your styling, see if maybe using px like in the Figma will fix it. 
Also, the text "Send Reset Link" on the button seems a bit small and some of the font weights seem a bit off.

2023-11-05 23:08 UTC, SPTLAbron commented
I removed the imports for the fonts, renamed the image, moved it into the assets folder, and changed the images for each page.

2023-11-08 08:00 UTC, yieb approved these changes

2023-11-08 08:02 UTC, merged